eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
spring:
  cloud:
        config:
                label: master
                profile: dev
                uri: http://localhost:8770/