server:
  port: 9000
spring:
  application:
    name: authority-server
battcn:
  security:
    token:
      expiration-time: 10 # 分钟 1440
      refresh-exp-time: 30 # 分钟 2880
      issuer: http://blog.battcn.com
      signing-key: battcn