server:
  port: 9000
spring:
  application:
    name: authority-server
  jpa:
    properties:
      hibernate:
        dialect: com.wen.sys.MySQL5DialectWithoutFK
        hbm2ddl:
          auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/as?allowMultiQueries=true
    username: root
    password: 123
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true





battcn:
  security:
    token:
      expiration-time: 10 # 分钟 1440
      refresh-exp-time: 30 # 分钟 2880
      issuer: http://blog.battcn.com
      signing-key: battcn