spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        health-check-interval: 10s
        instance-id: ${spring.application.name}
        health-check-path: /actuator/health
server:
  port: 8781